---
- hosts: jitsi
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - vars/secrets.yml
  roles:
    - common
    - mosh
    - swap
    - nginx
    - letsencrypt-nginx
    - letsencrypt
    - jitsi-meet
    - monitored
  vars:
    domain: "{{jitsi_domain}}"
    letsencrypt_domains:
      - "{{jitsi_domain}}"
      - "{{jitsi_auth_domain}}"
      - "{{jitsi_conference_domain}}"
      - "{{jitsi_videobridge_domain}}"
      - "{{jitsi_focus_domain}}"
