---
# Install python2.7 and aptitude on the host first thing -- ansible won't be
# fully functional until then.

- hosts: all
  gather_facts: False
  tasks:
   - name: apt-get update
     raw: apt-get update -qq
   - name: Install python2.7 and aptitude
     raw: apt-get install -qq python2.7 aptitude python-simplejson
